version: '3'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
                - ./backend/env/.env.prod
        command: gunicorn --bind 0.0.0.0:5000 app:application
        expose:
            - 5000
    frontend:
        build: ./frontend
        ports:
            - 4000:80
        depends_on:
            - backend
