version: '3.8'

services:
  redis:
    image: redis
  db:
    image: postgres
    expose:
      - 5432
  celery:
    build:
      context: ./backend
    depends_on:
      - redis
      - db
      - db_data
    command: celery -A app.celery worker
  backend:
    build:
      context: ./backend
    depends_on:
      - redis
      - celery
      - db
      - db_data
  frontend:
    build: 
      context: ./frontend
    depends_on:
      - redis
      - celery
      - backend
      - db
      - db_data

